# ----
# Site

title: Electra API
description: Electra API documentation.
url: https://electra-api-doc.herokuapp.com
google_analytics_key:
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position: 1
  address:
    title: Addresses
    position: 2
  seller:
    title: Sellers
    position: 3
  transaction:
    title: Transactions
    position: 4
  user:
    title: Users
    position: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - LICENSE
  - README.md
  # https://github.com/jekyll/jekyll/issues/2938#issuecomment-56237068
  - vendor

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
